
class Constants(object):

    USER_STATUS_ACTIVE = 0
    USER_STATUS_INACTIVE = 1

    USER_ROLE_ADMIN = 1
    USER_ROLE_USER = 2

    ORGANIZATION_STATUS_ACTIVE = 0
    ORGANIZATION_STATUS_INACTIVE = 1
